traefik:
  image: traefik
  ports:
    - "80:80"
    - "443:443"
    - "127.0.0.1:8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config/traefik.toml:/etc/traefik/traefik.toml
    - ./config/acme.json:/etc/traefik/acme.json
