logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[web]
  address = ":8080"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true

[traefikLog]
  filePath = "/var/log/traefik.log"