logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"

  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = """"""
    keyFile = """"""
  [entryPoints.other-https]
    address = ":4443"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "docker.localhost"
watch = true

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"